# Dataset config cho YOLOv11 - Biển báo giao thông Việt Nam

train: C:\Users\Admin\XLA-N5\xla_nhandienbienbaogiaothong\archive\output\train\images
val: C:\Users\Admin\XLA-N5\xla_nhandienbienbaogiaothong\archive\output\val\images
test: C:\Users\Admin\XLA-N5\xla_nhandienbienbaogiaothong\archive\output\test\images

nc: 5  # số lớp
names:
  0: Biển báo cấm
  1: Biển báo nguy hiểm và cảnh báo
  2: Biển báo hiệu lệnh
  3: Biển báo chỉ báo khu vực
  4: Biển chỉ dẫn
