# configs/data.yaml
# Đường dẫn dataset
path: ../datasets/split_dataset  

# Chia tập train / val / test
train: train/images
val: val/images
test: test/images

# Số class
nc: 5

names:
  - stop
  - speed_limit_30
  - speed_limit_40
  - speed_limit_50
  - yield
  - no_entry
  - traffic_light
